# render.yaml
services:
  - type: web
    name: crypto-liquidity-predictor
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      chmod a+x app/setup.sh
      app/setup.sh
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0